channels:
  - defaults
  - conda-forge
dependencies:
- python==3.10.6
- pip==22.0.4
- pip:
  - numpy==1.21.6
  - pandas==1.3.5
  - matplotlib==3.5.2
  - seaborn==0.11.2
  - tensorflow==2.9.1
  - sklearn==0.0
  - ipywidgets==8.0.2
  - nltk==3.7
  - voila==0.3.8
